# Generated by Django migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=100)),
                ('frame_id', models.CharField(blank=True, default='', max_length=50)),
                ('alert_type', models.CharField(choices=[('COMBINED_THREAT', 'Combined Threat'), ('WEAPON_DETECTED', 'Weapon Detected'), ('FACE_RECOGNIZED', 'Face Recognized')], default='COMBINED_THREAT', max_length=50)),
                ('identities', models.JSONField(default=list)),
                ('node_ip', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='nodes.node')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
