listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
    auth {
        enabled     on;
        username    cvsentry_srs;
        password    __SRS_API_PASSWORD__;
    }
}

rtc_server {
    enabled         on;
    listen          8000;
    candidate       $CANDIDATE;
}

vhost __defaultVhost__ {
    tcp_nodelay     on;
    min_latency     on;

    play {
        gop_cache       off;
        queue_length    10;
        mw_latency      100;
    }

    publish {
        mr              off;
    }

    http_hooks {
        enabled         on;
        on_play         http://core:8000/internal/srs/on_play/;
        on_publish      http://core:8000/internal/srs/on_publish/;
        on_stop         http://core:8000/internal/srs/on_stop/;
        on_unpublish    http://core:8000/internal/srs/on_unpublish/;
        on_hls          http://core:8000/internal/srs/on_hls/;
    }

    rtc {
        enabled         on;
        rtmp_to_rtc     on;
        rtc_to_rtmp     on;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    hls {
        enabled             on;
        hls_fragment        2;
        hls_window          0;
        hls_path            ./objs/nginx/html/records;
        hls_m3u8_file       [app]/[stream].m3u8;
        hls_ts_file         [app]/[stream]-[seq].ts;
        hls_cleanup         off;
        hls_wait_keyframe   on;
    }
}
