listening-port=3478
tls-listening-port=5349
realm=__TURN_REALM__
use-auth-secret
static-auth-secret=__TURN_SHARED_SECRET__
external-ip=__TURN_EXTERNAL_IP__
min-port=__TURN_MIN_PORT__
max-port=__TURN_MAX_PORT__
verbose
