# Generated by Django 6.0.5 on 2026-05-08 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0002_node_webrtc_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_id', models.CharField(max_length=100)),
                ('srs_stream_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('completed', 'Completed'), ('failed', 'Failed')], default='recording', max_length=20)),
                ('minio_bucket', models.CharField(default='cvsentry-recordings', max_length=100)),
                ('minio_prefix', models.CharField(blank=True, default='', max_length=500)),
                ('total_duration_ms', models.BigIntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('segment_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='nodes.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FrameMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.BigIntegerField()),
                ('timestamp_micros', models.BigIntegerField(db_index=True)),
                ('detections', models.JSONField(default=dict)),
                ('severity', models.CharField(default='normal', max_length=10)),
                ('has_threat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_metadata', to='recordings.recording')),
            ],
            options={
                'ordering': ['timestamp_micros'],
            },
        ),
        migrations.CreateModel(
            name='RecordingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.IntegerField()),
                ('minio_key', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='recordings.recording')),
            ],
            options={
                'ordering': ['segment_index'],
            },
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_id', models.CharField(max_length=100)),
                ('srs_stream_id', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_streams', to='nodes.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('node', 'camera_id')},
            },
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['user', 'started_at'], name='recordings__user_id_e79f23_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['node', 'camera_id'], name='recordings__node_id_80c2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='framemetadata',
            index=models.Index(fields=['recording', 'timestamp_micros'], name='recordings__recordi_d76457_idx'),
        ),
        migrations.AddIndex(
            model_name='framemetadata',
            index=models.Index(fields=['recording', 'severity'], name='recordings__recordi_af7f48_idx'),
        ),
        migrations.AddIndex(
            model_name='framemetadata',
            index=models.Index(fields=['recording', 'has_threat'], name='recordings__recordi_c4b206_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recordingsegment',
            unique_together={('recording', 'segment_index')},
        ),
    ]
