# Generated by Django 6.0.5 on 2026-06-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='mp4_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
