# Generated by Django 5.2.7 on 2026-02-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
