# Generated by Django 6.0.5 on 2026-05-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='webrtc_port',
            field=models.IntegerField(default=8001),
        ),
    ]
