# Generated by Django 5.2.7 on 2026-05-04 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('qdrant_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='faces/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Face Identities',
            },
        ),
    ]
