# Generated by Django 5.2.7 on 2026-05-04 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceidentity',
            name='image',
        ),
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='faces.faceidentity')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
